version: '3.8'

services:
  # Cấu hình PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: visuallab-postgres
    restart: always
    environment:
      POSTGRES_DB: edulab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Cấu hình Redis
  redis:
    image: redis:7-alpine
    container_name: visuallab-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
