const LABS_DATA = [
  {
    id: 'sim-speed-measurement',
    title: 'Bài 6: Đo Tốc Độ Vật Chuyển Động Thẳng',
    subject: 'Vật lý',
    domain: 'Cơ Học & Năng Lượng',
    grade: 'Lớp 10',
    difficulty: 'EASY',
    chapter: 'Chương II: Động Học',
    description: 'Trang 28 SGK. Đo thời gian bi thép lăn trên máng nghiêng qua 2 cổng quang điện để xác định tốc độ trung bình và gia tốc.',
    tags: 'GDPT 2018,SGK T28,Kéo thả,Cổng quang điện',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80',
    route: '/lab/speed-measurement',
    simulationType: 'CUSTOM_CANVAS',
    status: 'PUBLISHED',
  },
  {
    id: 'sim-free-fall',
    title: 'Bài 14: Đo Gia Tốc Rơi Tự Do',
    subject: 'Vật lý',
    domain: 'Cơ Học & Năng Lượng',
    grade: 'Lớp 10',
    difficulty: 'MEDIUM',
    chapter: 'Chương III: Động Lực Học',
    description: 'Trang 57 SGK. Nam châm điện ngắt điện thả bi thép rơi tự do qua cổng quang điện, tự động tính gia tốc g.',
    tags: 'GDPT 2018,SGK T57,Kéo thả,Rơi tự do',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&auto=format&fit=crop&q=80',
    route: '/lab/free-fall',
    simulationType: 'STEP_WORKFLOW',
    status: 'PUBLISHED',
  },
  {
    id: 'sim-friction-coefficient',
    title: 'Bài 21: Đo Hệ Số Ma Sát Trượt',
    subject: 'Vật lý',
    domain: 'Cơ Học & Năng Lượng',
    grade: 'Lớp 10',
    difficulty: 'MEDIUM',
    chapter: 'Chương IV: Năng Lượng & Ma Sát',
    description: 'Trang 83 SGK. Dùng lực kế kéo khối gỗ gắn quả cân trượt đều trên mặt bàn để đo hệ số ma sát μ.',
    tags: 'GDPT 2018,SGK T83,Kéo thả,Lực kế',
    thumbnailUrl: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?w=600&auto=format&fit=crop&q=80',
    route: '/lab/sliding-friction',
    simulationType: 'CUSTOM_CANVAS',
    status: 'PUBLISHED',
  },
  {
    id: 'sim-momentum-collision',
    title: 'Bài 30: Khảo Sát Động Lượng & Va Chạm',
    subject: 'Vật lý',
    domain: 'Cơ Học & Năng Lượng',
    grade: 'Lớp 10',
    difficulty: 'HARD',
    chapter: 'Chương V: Động Lượng & Va Chạm',
    description: 'Trang 117 SGK. Mô phỏng va chạm 2 xe trượt trên đệm không khí, kiểm chứng định luật bảo toàn động lượng.',
    tags: 'GDPT 2018,SGK T117,Tham số,Va chạm',
    thumbnailUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    route: '/lab/momentum-collision',
    simulationType: 'CUSTOM_CANVAS',
    status: 'PUBLISHED',
  },
  {
    id: 'sim-hooke-law',
    title: 'Bài 38: Độ Biến Dạng Lò Xo (Định Luật Hooke)',
    subject: 'Vật lý',
    domain: 'Cơ Học & Năng Lượng',
    grade: 'Lớp 10',
    difficulty: 'EASY',
    chapter: 'Chương VI: Biến Dạng & Đàn Hồi',
    description: 'Trang 148 SGK. Treo quả cân lên lò xo xoắn, đo độ giãn Δl và tính độ cứng k.',
    tags: 'GDPT 2018,SGK T148,Kéo thả,Hooke',
    thumbnailUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=600&auto=format&fit=crop&q=80',
    route: '/lab/spring-mass',
    simulationType: 'CUSTOM_CANVAS',
    status: 'PUBLISHED',
  },
  {
    id: 'sim-simple-pendulum',
    title: 'Bài 7: Khảo Sát Dao Động Con Lắc Đơn',
    subject: 'Vật lý',
    domain: 'Cơ Học & Năng Lượng',
    grade: 'Lớp 11',
    difficulty: 'EASY',
    chapter: 'Chương I: Dao Động Cơ',
    description: 'Trang 29 SGK. Khảo sát chu kỳ T = 2π√(l/g) của con lắc đơn theo chiều dài dây l.',
    tags: 'GDPT 2018,SGK T29,Tham số,Con lắc đơn',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&auto=format&fit=crop&q=80',
    route: '/lab/simple-pendulum',
    simulationType: 'PHET_EMBED',
    status: 'PUBLISHED',
  },
  {
    id: 'sim-sound-resonance',
    title: 'Bài 5: Đo Tốc Độ Truyền Âm (Ống Cộng Hưởng)',
    subject: 'Vật lý',
    domain: 'Sóng & Âm Học',
    grade: 'Lớp 11',
    difficulty: 'MEDIUM',
    chapter: 'Chương II: Sóng',
    description: 'Trang 22 SGK. Mô phỏng 3D ống thủy tinh cộng hưởng âm thanh, nâng hạ cột nước để đo tốc độ truyền âm v.',
    tags: 'GDPT 2018,SGK T22,Three.js,Tone.js',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    route: '/lab/sound-resonance',
    simulationType: 'THREE_JS',
    status: 'PUBLISHED',
  },
  {
    id: 'sim-young-interference',
    title: 'Bài 12: Đo Bước Sóng Ánh Sáng (Khe Y-âng)',
    subject: 'Vật lý',
    domain: 'Quang Học',
    grade: 'Lớp 11',
    difficulty: 'HARD',
    chapter: 'Chương II: Sóng',
    description: 'Trang 50 SGK. Chiếu laser qua khe kép Y-âng, dùng thước kẹp đo khoảng vân i để tính bước sóng λ.',
    tags: 'GDPT 2018,SGK T50,Kéo thả,Giao thoa',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=600&auto=format&fit=crop&q=80',
    route: '/lab/wave-interference',
    simulationType: 'CUSTOM_CANVAS',
    status: 'PUBLISHED',
  },
  {
    id: 'sim-refraction',
    title: 'Bài 21: Đo Chiết Suất Của Nước & Khúc Xạ',
    subject: 'Vật lý',
    domain: 'Quang Học',
    grade: 'Lớp 11',
    difficulty: 'MEDIUM',
    chapter: 'Chương III: Quang Học',
    description: 'Trang 85 SGK. Chiếu tia laser qua bán trụ thủy tinh để xác định góc khúc xạ r và chiết suất n.',
    tags: 'GDPT 2018,SGK T85,Tham số,Khúc xạ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=600&auto=format&fit=crop&q=80',
    route: '/lab/refraction',
    simulationType: 'PHET_EMBED',
    status: 'PUBLISHED',
  },
  {
    id: 'sim-emf-internal-r',
    title: 'Bài 19: Đo Suất Điện Động E & Điện Trở Trong r',
    subject: 'Vật lý',
    domain: 'Điện & Từ Học',
    grade: 'Lớp 11',
    difficulty: 'MEDIUM',
    chapter: 'Chương IV: Dòng Điện Không Đổi',
    description: 'Trang 76 SGK. Khảo sát đặc tuyến U-I của nguồn Pin DC bằng biến trở con chạy và công tắc.',
    tags: 'GDPT 2018,SGK T76,Kéo thả,Nguồn pin',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517420704952-d9f39e95b43e?w=600&auto=format&fit=crop&q=80',
    route: '/lab/emf-internal-r',
    simulationType: 'CUSTOM_CANVAS',
    status: 'PUBLISHED',
  },
  {
    id: 'sim-dc-circuit',
    title: 'Mạch Điện Một Chiều & Định Luật Ohm',
    subject: 'Vật lý',
    domain: 'Điện & Từ Học',
    grade: 'Lớp 11',
    difficulty: 'EASY',
    chapter: 'Chương IV: Dòng Điện Không Đổi',
    description: 'Mô phỏng lắp ráp mạch điện Pin, Điện trở, Ampe kế, Vôn kế và kiểm chứng định luật Ohm I = U / R.',
    tags: 'GDPT 2018,Canvas,Điện học,Định luật Ohm',
    thumbnailUrl: 'https://images.unsplash.com/photo-1555664424-778a1e5e1b48?w=600&auto=format&fit=crop&q=80',
    route: '/lab/dc-circuit',
    simulationType: 'CUSTOM_CANVAS',
    status: 'PUBLISHED',
  },
  {
    id: 'sim-specific-heat',
    title: 'Bài 3: Đo Nhiệt Dung Riêng Của Nước',
    subject: 'Vật lý',
    domain: 'Nhiệt Học',
    grade: 'Lớp 12',
    difficulty: 'MEDIUM',
    chapter: 'Chương I: Vật Lý Nhiệt',
    description: 'Trang 15 SGK. Dùng dây điện trở đun nước trong bình nhiệt lượng kế, đo công suất P và nhiệt độ T.',
    tags: 'GDPT 2018,SGK T15,Tham số,Nhiệt học',
    thumbnailUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=600&auto=format&fit=crop&q=80',
    route: '/lab/specific-heat',
    simulationType: 'CUSTOM_CANVAS',
    status: 'PUBLISHED',
  },
  {
    id: 'sim-latent-heat',
    title: 'Bài 4: Đo Nhiệt Nóng Chảy Nước Đá',
    subject: 'Vật lý',
    domain: 'Nhiệt Học',
    grade: 'Lớp 12',
    difficulty: 'MEDIUM',
    chapter: 'Chương I: Vật Lý Nhiệt',
    description: 'Trang 19 SGK. Khảo sát quá trình nóng chảy của nước đá bằng bình nhiệt lượng kế và nhiệt kế điện tử.',
    tags: 'GDPT 2018,SGK T19,Tham số,Nước đá',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    route: '/lab/latent-heat',
    simulationType: 'CUSTOM_CANVAS',
    status: 'PUBLISHED',
  },
  {
    id: 'sim-boyle-mariotte',
    title: 'Bài 7: Quá Trình Đẳng Nhiệt (Boyle - Mariotte)',
    subject: 'Vật lý',
    domain: 'Nhiệt Học',
    grade: 'Lớp 12',
    difficulty: 'HARD',
    chapter: 'Chương II: Khí Lý Tưởng',
    description: 'Trang 30 SGK. Nén piston trong xy-lanh khí và đọc áp kế để kiểm chứng p·V = const.',
    tags: 'GDPT 2018,SGK T30,Tham số,Đẳng nhiệt',
    thumbnailUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    route: '/lab/boyle-mariotte',
    simulationType: 'CUSTOM_CANVAS',
    status: 'PUBLISHED',
  },
  {
    id: 'sim-electromagnetic-induction',
    title: 'Bài 12: Khảo Sát Cảm Ứng Điện Từ',
    subject: 'Vật lý',
    domain: 'Điện & Từ Học',
    grade: 'Lớp 12',
    difficulty: 'MEDIUM',
    chapter: 'Chương III: Từ Trường',
    description: 'Trang 52 SGK. Di chuyển nam châm vĩnh cửu qua cuộn dây cảm ứng để quan sát kim điện kế G lệch.',
    tags: 'GDPT 2018,SGK T52,Kéo thả,Cảm ứng từ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1555664424-778a1e5e1b48?w=600&auto=format&fit=crop&q=80',
    route: '/lab/induction',
    simulationType: 'CUSTOM_CANVAS',
    status: 'PUBLISHED',
  },
  {
    id: 'workbench-universal',
    title: 'Bàn Thí Nghiệm Tự Do (Universal Sandbox)',
    subject: 'Vật lý',
    domain: 'Cơ - Điện - Quang',
    grade: 'Lớp 10 - 12',
    difficulty: 'HARD',
    chapter: 'Sandbox Sáng Tạo',
    description: 'Tự do chọn và ghép nối các linh kiện PhET SceneryStack thuộc 3 môn Cơ - Điện - Quang.',
    tags: 'Sandbox,PhET,Sáng tạo,Toàn diện',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
    route: '/workbench/universal',
    simulationType: 'CUSTOM_CANVAS',
    status: 'PUBLISHED',
  },
];

async function syncLabs() {
  console.log('Starting sync for 16 curriculum labs...');
  for (const lab of LABS_DATA) {
    try {
      const res = await fetch('http://localhost:8080/api/labs', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(lab),
      });
      if (res.ok) {
        console.log(`✓ Synced: ${lab.id} - ${lab.title}`);
      } else {
        console.error(`✗ Failed to sync: ${lab.id}`, res.statusText);
      }
    } catch (err) {
      console.error(`Error syncing ${lab.id}:`, err);
    }
  }
  console.log('Sync complete!');
}

syncLabs();
