spring:
  application:
    name: backend

  # ===============================
  # CẤU HÌNH POSTGRESQL
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/visuallab_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # ===============================
  # CẤU HÌNH JPA / HIBERNATE
  # ===============================
  jpa:
    hibernate:
      ddl-auto: update # Tạo/Cập nhật bảng tự động dựa trên Entity. Khuyến cáo đổi thành 'validate' ở môi trường production
    show-sql: true     # Hiển thị SQL query trên console
    properties:
      hibernate:
        format_sql: true

  # ===============================
  # CẤU HÌNH REDIS
  # ===============================
  data:
    redis:
      host: localhost
      port: 6379
      # password: your_redis_password_if_any

server:
  port: 8080
