import type { IInstrumentConfig } from './types';

/**
 * Registry chứa Cấu hình & Schema Tham số chuẩn cho tất cả Tool ID trong SGK GDPT 2018.
 * TUYỆT ĐỐI KHÔNG HARDCODE TRONG LOGIC - Tất cả đều lấy từ Registry này hoặc từ DB JSONB.
 */
export const INSTRUMENT_REGISTRY: Record<string, IInstrumentConfig> = {
  // --- ĐỘNG HỌC & CƠ HỌC ---
  PHOTOGATE_SENSOR: {
    toolId: 'PHOTOGATE_SENSOR',
    name: 'Cổng quang điện',
    category: 'KINEMATICS',
    params: {
      beamWidth: {
        id: 'beamWidth',
        name: 'Độ rộng chùm tia',
        symbol: 'd',
        unit: 'mm',
        min: 1,
        max: 10,
        step: 0.5,
        defaultValue: 5,
        value: 5,
      },
    },
  },
  DIGITAL_TIMER: {
    toolId: 'DIGITAL_TIMER',
    name: 'Đồng hồ hiện số',
    category: 'KINEMATICS',
    params: {
      precision: {
        id: 'precision',
        name: 'Độ chính xác',
        symbol: 'dt',
        unit: 's',
        min: 0.001,
        max: 0.01,
        step: 0.001,
        defaultValue: 0.001,
        value: 0.001,
      },
    },
  },
  STEEL_BALL: {
    toolId: 'STEEL_BALL',
    name: 'Bi thép',
    category: 'KINEMATICS',
    params: {
      mass: {
        id: 'mass',
        name: 'Khối lượng bi',
        symbol: 'm',
        unit: 'kg',
        min: 0.01,
        max: 0.5,
        step: 0.01,
        defaultValue: 0.05,
        value: 0.05,
      },
      radius: {
        id: 'radius',
        name: 'Bán kính',
        symbol: 'r',
        unit: 'cm',
        min: 0.5,
        max: 5.0,
        step: 0.1,
        defaultValue: 1.0,
        value: 1.0,
      },
    },
  },
  HELICAL_SPRING: {
    toolId: 'HELICAL_SPRING',
    name: 'Lò xo xoắn',
    category: 'DYNAMICS',
    params: {
      springConstant: {
        id: 'springConstant',
        name: 'Độ cứng lò xo',
        symbol: 'k',
        unit: 'N/m',
        min: 10,
        max: 200,
        step: 5,
        defaultValue: 50,
        value: 50,
      },
      naturalLength: {
        id: 'naturalLength',
        name: 'Chiều dài tự nhiên',
        symbol: 'l_0',
        unit: 'cm',
        min: 10,
        max: 50,
        step: 1,
        defaultValue: 20,
        value: 20,
      },
    },
  },

  // --- ĐIỆN HỌC ---
  DC_POWER_SUPPLY: {
    toolId: 'DC_POWER_SUPPLY',
    name: 'Nguồn Pin DC',
    category: 'ELECTRICITY',
    params: {
      emf: {
        id: 'emf',
        name: 'Suất điện động',
        symbol: 'E',
        unit: 'V',
        min: 1.0,
        max: 24.0,
        step: 0.5,
        defaultValue: 1.5,
        value: 1.5,
      },
      internalResistance: {
        id: 'internalResistance',
        name: 'Điện trở trong',
        symbol: 'r',
        unit: 'Ohm',
        min: 0.0,
        max: 5.0,
        step: 0.1,
        defaultValue: 0.5,
        value: 0.5,
      },
    },
  },
  VOLTMETER_DC: {
    toolId: 'VOLTMETER_DC',
    name: 'Vôn kế DC',
    category: 'ELECTRICITY',
    params: {
      range: {
        id: 'range',
        name: 'Thang đo cực đại',
        symbol: 'U_max',
        unit: 'V',
        min: 1.0,
        max: 30.0,
        step: 1.0,
        defaultValue: 3.0,
        value: 3.0,
      },
      internalResistance: {
        id: 'internalResistance',
        name: 'Điện trở trong vôn kế',
        symbol: 'R_V',
        unit: 'Ohm',
        min: 10000,
        max: 1000000,
        step: 5000,
        defaultValue: 50000,
        value: 50000,
      },
    },
  },
  AMMETER_DC: {
    toolId: 'AMMETER_DC',
    name: 'Ampe kế DC',
    category: 'ELECTRICITY',
    params: {
      range: {
        id: 'range',
        name: 'Thang đo cực đại',
        symbol: 'I_max',
        unit: 'A',
        min: 0.1,
        max: 5.0,
        step: 0.1,
        defaultValue: 0.5,
        value: 0.5,
      },
      internalResistance: {
        id: 'internalResistance',
        name: 'Điện trở trong ampe kế',
        symbol: 'R_A',
        unit: 'Ohm',
        min: 0.01,
        max: 1.0,
        step: 0.01,
        defaultValue: 0.05,
        value: 0.05,
      },
    },
  },
  RHEOSTAT_VARIABLE: {
    toolId: 'RHEOSTAT_VARIABLE',
    name: 'Biến trở con chạy',
    category: 'ELECTRICITY',
    params: {
      maxResistance: {
        id: 'maxResistance',
        name: 'Điện trở tối đa',
        symbol: 'R_max',
        unit: 'Ohm',
        min: 10,
        max: 500,
        step: 10,
        defaultValue: 100,
        value: 100,
      },
      currentResistance: {
        id: 'currentResistance',
        name: 'Điện trở thiết lập',
        symbol: 'R_cur',
        unit: 'Ohm',
        min: 0,
        max: 100,
        step: 1,
        defaultValue: 20,
        value: 20,
      },
    },
  },

  // --- QUANG HỌC ---
  LASER_SOURCE_RGB: {
    toolId: 'LASER_SOURCE_RGB',
    name: 'Nguồn phát Laser',
    category: 'OPTICS',
    params: {
      wavelength: {
        id: 'wavelength',
        name: 'Bước sóng ánh sáng',
        symbol: 'lambda',
        unit: 'nm',
        min: 380,
        max: 750,
        step: 1,
        defaultValue: 632.8,
        value: 632.8,
      },
      power: {
        id: 'power',
        name: 'Công suất laser',
        symbol: 'P',
        unit: 'mW',
        min: 1,
        max: 50,
        step: 1,
        defaultValue: 5,
        value: 5,
      },
    },
  },

  // --- ÂM HỌC ---
  RESONANCE_TUBE: {
    toolId: 'RESONANCE_TUBE',
    name: 'Ống cộng hưởng âm',
    category: 'ACOUSTICS',
    params: {
      tubeLength: {
        id: 'tubeLength',
        name: 'Chiều dài ống',
        symbol: 'L',
        unit: 'cm',
        min: 30,
        max: 120,
        step: 1,
        defaultValue: 100,
        value: 100,
      },
      waterLevel: {
        id: 'waterLevel',
        name: 'Mức nước',
        symbol: 'h_w',
        unit: 'cm',
        min: 0,
        max: 100,
        step: 0.1,
        defaultValue: 30,
        value: 30,
      },
    },
  },
  AUDIO_GENERATOR: {
    toolId: 'AUDIO_GENERATOR',
    name: 'Máy phát tần số âm',
    category: 'ACOUSTICS',
    params: {
      frequency: {
        id: 'frequency',
        name: 'Tần số phát',
        symbol: 'f',
        unit: 'Hz',
        min: 100,
        max: 2000,
        step: 5,
        defaultValue: 440,
        value: 440,
      },
    },
  },
};
